/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Project;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Book book1 = new Book("Giver",99);
        System.out.println(book1.toString());
        System.out.println(new App().getGreeting());
    }
}
